# https://github.com/vercel/next.js/blob/canary/examples/with-docker-compose/docker-compose.dev.yml
version: '3.8'
services:
  app:
    image: gpt35-pdf-chatbot:v1.0
    container_name: gpt35-pdf-chatbot-app
    build:
      context: ./
      dockerfile: Dockerfile
      target: runner 
    volumes:
      - .:/app
    command: npm run dev
    ports:
      - "3000:3000"
    environment:
      - NODE_OPTIONS=--dns-result-order=ipv4first
